// Centralized data for CSK players and schedule
const cskData = {
    players: {
        // WICKET-KEEPERS
        "msd": { id: "msd", name: "MS Dhoni", role: "Wicket-Keeper / Batter", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team1playerImgNoBg_1773206232679.png", bio: "The legendary former captain who led CSK to multiple IPL titles. Known as 'Captain Cool', Dhoni remains a pivotal figure in the squad, offering unparalleled experience, lightning-fast stumpings, and explosive lower-order finishing.", stats: { matches: 278, innings: 242, runs: 5439, highScore: 84, average: 38.3, strikeRate: 137.46, centuries: 0, fifties: 24 } },
        "sanju": { id: "sanju", name: "Sanju Samson", role: "Wicket-Keeper / Batter", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Offbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team50playerImgNoBg_1773207257969.png", bio: "A dynamic top-order batsman who joined CSK in 2026. He has been in stellar form, anchoring innings and accelerating with immense power, recently scoring his second century of the season.", stats: { matches: 184, innings: 180, runs: 5008, highScore: 119, average: 31.7, strikeRate: 140.71, centuries: 5, fifties: 26 } },
        "urvil": { id: "urvil", name: "Urvil Patel", role: "Wicket-Keeper / Batter", battingStyle: "Right-hand Bat", bowlingStyle: "-", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team49playerImgNoBg_1773208996000.png", bio: "A promising wicket-keeper batsman.", stats: { matches: 4, innings: 3, runs: 68, highScore: 37, average: 22.67, strikeRate: 212.50, centuries: 0, fifties: 0 } },
        "kartik": { id: "kartik", name: "Kartik Sharma", role: "Wicket-Keeper / Batter", battingStyle: "Left-hand Bat", bowlingStyle: "-", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team53playerImgNoBg_1773206702889.png", bio: "A solid wicket-keeper.", stats: { matches: 5, innings: 4, runs: 43, highScore: 18, average: 10.75, strikeRate: 107.50, centuries: 0, fifties: 0 } },
        // BATTERS
        "ruturaj": { id: "ruturaj", name: "Ruturaj Gaikwad", role: "Captain / Batter", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Offbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team4playerImgNoBg_1773207316332.png", bio: "Ruturaj Gaikwad is the current captain of the Chennai Super Kings. Known for his elegant stroke play and calm demeanor, he took over the reins from MS Dhoni. He has been a consistent run-scorer at the top of the order.", stats: { matches: 79, innings: 78, runs: 2616, highScore: 108, average: 37.91, strikeRate: 136.75, centuries: 2, fifties: 20 } },
        "brevis": { id: "brevis", name: "Dewald Brevis", role: "Batter", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Legbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team46playerImgNoBg_1773208945125.png", bio: "Known as 'Baby AB', Brevis is an explosive young talent with an incredible array of shots.", stats: { matches: 21, innings: 19, runs: 517, highScore: 57, average: 27.21, strikeRate: 151.61, centuries: 0, fifties: 2 } },
        "ayush": { id: "ayush", name: "Ayush Mhatre", role: "Batter", battingStyle: "Right-hand Bat", bowlingStyle: "-", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team45playerImgNoBg_1773208902161.png", bio: "A talented top-order batsman.", stats: { matches: 13, innings: 13, runs: 441, highScore: 94, average: 33.92, strikeRate: 183.75, centuries: 0, fifties: 3 } },
        "sarfaraz": { id: "sarfaraz", name: "Sarfaraz Khan", role: "Batter", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Offbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team58playerImgNoBg_1773379183176.png", bio: "An unorthodox and highly innovative middle-order batter known for playing sweep shots.", stats: { matches: 58, innings: 43, runs: 746, highScore: 67, average: 23.31, strikeRate: 137.64, centuries: 0, fifties: 2 } },
        // BOWLERS
        "noor": { id: "noor", name: "Noor Ahmad", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Left-arm Wrist Spin", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team12playerImgNoBg_1773208221215.png", bio: "A highly talented young wrist spinner from Afghanistan, providing a mystery element to the CSK bowling attack.", stats: { matches: 45, innings: 44, wickets: 54, economy: 8.23, FourWickets: 2, FiveWickets: 0 } },
        "khaleel": { id: "khaleel", name: "Khaleel Ahmed", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Left-arm Fast-medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team13playerImgNoBg_1773379207442.png", bio: "A left-arm pacer capable of swinging the new ball.", stats: { matches: 76, innings: 76, wickets: 91, economy: 8.96, FourWickets: 0, FiveWickets: 0 } },
        "anshul": { id: "anshul", name: "Anshul Kamboj", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team43playerImgNoBg_1773209148564.png", bio: "An up-and-coming pace bowler.", stats: { matches: 19, innings: 18, wickets: 24, economy: 9.03, FourWickets: 0, FiveWickets: 0 } },
        "gurjapneet": { id: "gurjapneet", name: "Gurjapneet Singh", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Left-arm Medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team15playerImgNoBg_1773208406237.png", bio: "A young left-arm pace prospect.", stats: { matches: 5, innings: 4, wickets: 3, economy: 9.22, FourWickets: 0, FiveWickets: 0 } },
        "mukesh": { id: "mukesh", name: "Mukesh Choudhary", role: "Bowler", battingStyle: "Left-hand Bat", bowlingStyle: "Left-arm Fast-medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team24playerImgNoBg_1773208579668.png", bio: "A skilled left-arm pacer who excels in the powerplay.", stats: { matches: 18, innings: 18, wickets: 20, economy: 9.81, FourWickets: 1, FiveWickets: 0 } },
        "akeal": { id: "akeal", name: "Akeal Hosein", role: "Bowler", battingStyle: "Left-hand Bat", bowlingStyle: "Slow Left-arm Orthodox", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team51playerImgNoBg_1773206570529.png", bio: "An accurate left-arm spinner from the West Indies.", stats: { matches: 5, innings: 4, wickets: 6, economy: 7.36, FourWickets: 1, FiveWickets: 0 } },
        "henry": { id: "henry", name: "Matt Henry", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Fast-medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team55playerImgNoBg_1773206880148.png", bio: "A seasoned New Zealand pacer with great control.", stats: { matches: 9, innings: 9, wickets: 4, economy: 11.52, FourWickets: 0, FiveWickets: 0 } },
        "rahul": { id: "rahul", name: "Rahul Chahar", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Legbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team56playerImgNoBg_1773206941099.png", bio: "An attacking leg-spinner.", stats: { matches: 80, innings: 79, wickets: 75, economy: 7.78, FourWickets: 1, FiveWickets: 0 } },
        "spencer": { id: "spencer", name: "Spencer Johnson", role: "Bowler", battingStyle: "Left-hand Bat", bowlingStyle: "Left-arm Fast", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team23playerImgNoBg_1774867441932.png", bio: "An express left-arm fast bowler from Australia.", stats: { matches: 9, innings: 9, wickets: 5, economy: 10.39, FourWickets: 0, FiveWickets: 0 } },
        "akash": { id: "akash", name: "Akash Madhwal", role: "Bowler", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Medium-fast", image: "https://image.telanganatoday.com/wp-content/uploads/2026/04/akash-madhwal_V_jpg--816x480-4g.webp?sw=1536&dsz=816x480&iw=615&p=false&r=1.25", bio: "A yorker specialist capable of bowling tough overs at the death.", stats: { matches: 17, innings: 17, wickets: 23, economy: 10.06, FourWickets: 1, FiveWickets: 1 } },
        // ALL-ROUNDERS
        "dube": { id: "dube", name: "Shivam Dube", role: "All-rounder", battingStyle: "Left-hand Bat", bowlingStyle: "Right-arm Medium", image: "https://documents.iplt20.com/ipl/IPLHeadshot2026/211.png", bio: "A destructive middle-order left-handed batsman, specifically lethal against spin bowling. Dube provides crucial overs of medium pace and acts as the enforcer in the middle overs.", stats: { matches: 87, runs: 1987, highScore: 95, average: 30.57, strikeRate: 143.57, centuries: 0, fifties: 10, wickets: 6, economy: 10.72 } },
        "jamie": { id: "jamie", name: "Jamie Overton", role: "All-rounder", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Fast", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team25playerImgNoBg_1773208844367.png", bio: "An express fast bowler and powerful lower-order hitter.", stats: { matches: 10, runs: 133, highScore: 43, average: 33.25, strikeRate: 152.87, centuries: 0, fifties: 0, wickets: 9, economy: 10.43 } },
        "ramakrishna": { id: "ramakrishna", name: "Ramakrishna Ghosh", role: "All-rounder", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team41playerImgNoBg_1773209044035.png", bio: "A versatile all-rounder.", stats: { matches: 0, runs: 0, highScore: 0, average: 0, strikeRate: 0, centuries: 0, fifties: 0, wickets: 0, economy: 0 } },
        "prashant": { id: "prashant", name: "Prashant Veer", role: "All-rounder", battingStyle: "Left-hand Bat", bowlingStyle: "Slow Left-arm Orthodox", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team59playerImgNoBg_1773207152530.png", bio: "A useful spin-bowling all-rounder.", stats: { matches: 2, runs: 49, highScore: 43, average: 49, strikeRate: 136.12, centuries: 0, fifties: 0, wickets: 0, economy: 0 } },
        "short": { id: "short", name: "Matthew Short", role: "All-rounder", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Offbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team54playerImgNoBg_1773206785917.png", bio: "An explosive opening batter and handy off-spinner from Australia.", stats: { matches: 8, runs: 153, highScore: 36, average: 19.13, strikeRate: 118.61, centuries: 0, fifties: 0, wickets: 0, economy: 0 } },
        "aman": { id: "aman", name: "Aman Khan", role: "All-rounder", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Medium", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team52playerImgNoBg_1773206632903.png", bio: "A powerful striker of the cricket ball.", stats: { matches: 12, runs: 115, highScore: 51, average: 12.78, strikeRate: 110.58, centuries: 0, fifties: 1, wickets: 0, economy: 0 } },
        "foulkes": { id: "foulkes", name: "Zak Foulkes", role: "All-rounder", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Medium-fast", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team57playerImgNoBg_1773206999966.png", bio: "A talented pace-bowling all-rounder.", stats: { matches: 0, runs: 0, highScore: 0, average: 0, strikeRate: 0, centuries: 0, fifties: 0, wickets: 4, economy: 0 } },
        "shreyas": { id: "shreyas", name: "Shreyas Gopal", role: "All-rounder", battingStyle: "Right-hand Bat", bowlingStyle: "Right-arm Legbreak", image: "https://gallery.chennaisuperkings.com/PROD/TEAM/Team16playerImgNoBg_1773208515368.png", bio: "A seasoned leg-spinner and handy lower-order batsman.", stats: { matches: 52, runs: 180, highScore: 24, average: 12.86, strikeRate: 106.51, centuries: 0, fifties: 0, wickets: 52, economy: 8.16 } }

    },
    schedule: [
        { date: "Mar 30, 2026", opponent: "RR", venue: "Barsapara Cricket Stadium, Guwahati", status: "Result", cskScore: "127", oppScore: "128/2", result: "RR won by 8 wkts" },
        { date: "Apr 3, 2026", opponent: "PBKS", venue: "M.A. Chidambaram Stadium, Chennai", status: "Result", cskScore: "209/5", oppScore: "210/5", result: "PBKS won by 5 wkts" },
        { date: "Apr 5, 2026", opponent: "RCB", venue: "M. Chinnaswamy Stadium, Bengaluru", status: "Result", cskScore: "207", oppScore: "250/3", result: "RCB won by 43 runs" },
        { date: "Apr 11, 2026", opponent: "DC", venue: "M.A. Chidambaram Stadium, Chennai", status: "Result", cskScore: "212/2", oppScore: "189", result: "CSK won by 23 runs" },
        { date: "Apr 14, 2026", opponent: "KKR", venue: "M.A. Chidambaram Stadium, Chennai", status: "Result", cskScore: "192/5", oppScore: "160/7", result: "CSK won by 32 runs" },
        { date: "Apr 18, 2026", opponent: "SRH", venue: "Rajiv Gandhi International Stadium, Hyderabad", status: "Result", cskScore: "184/8", oppScore: "194/9", result: "SRH won by 10 runs" },
        { date: "Apr 23, 2026", opponent: "MI", venue: "Wankhede Stadium, Mumbai", status: "Result", cskScore: "207/6", oppScore: "104", result: "CSK won by 103 runs" },
        { date: "Apr 26, 2026", opponent: "GT", venue: "M.A. Chidambaram Stadium, Chennai", status: "Upcoming", cskScore: "-", oppScore: "-", time: "Today, 3:30 PM" },
        { date: "May 2, 2026", opponent: "MI", venue: "M.A. Chidambaram Stadium, Chennai", status: "Upcoming", cskScore: "-", oppScore: "-", time: "7:30 PM" },
        { date: "May 5, 2026", opponent: "DC", venue: "Arun Jaitley Stadium, Delhi", status: "Upcoming", cskScore: "-", oppScore: "-", time: "7:30 PM" },
        { date: "May 10, 2026", opponent: "LSG", venue: "M.A. Chidambaram Stadium, Chennai", status: "Upcoming", cskScore: "-", oppScore: "-", time: "3:30 PM" },
        { date: "May 15, 2026", opponent: "LSG", venue: "Ekana Cricket Stadium, Lucknow", status: "Upcoming", cskScore: "-", oppScore: "-", time: "7:30 PM" },
        { date: "May 18, 2026", opponent: "SRH", venue: "M.A. Chidambaram Stadium, Chennai", status: "Upcoming", cskScore: "-", oppScore: "-", time: "7:30 PM" },
        { date: "May 21, 2026", opponent: "GT", venue: "Narendra Modi Stadium, Ahmedabad", status: "Upcoming", cskScore: "-", oppScore: "-", time: "7:30 PM" },
    ]
};

// Export for usage in other files
window.cskData = cskData;
